version: 2
jobs:
  tests:
    working_directory: ~/tests
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: test
          command: yarn test
  release:
    working_directory: ~/release
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: authenticate
          command: .circleci/authenticate.sh
      - run:
          name: release
          command: npm run-script release

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests
      - release:
          requires:
            - tests
          filters:
            branches:
              only: master
